name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pandamy619
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build postgre-docker-template
        run: |
          docker compose build . --tag ghcr.io/pandamy619/postgre-docker-template:latest
          docker compose run ghcr.io/pandamy619/postgre-docker-template:latest
          docker compose push ghcr.io/pandamy619/postgre-docker-template:latest
